### ISSUE TITLE
Meet Googles coding standards

### ISSUE THREAD

**Issue by cooper-roper** [climate-cooperative/home-energy-assessment-database#39]
## Description

Refactor and rewrite any code that does not meet Google's javascript coding standards

## Technical Notes

https://google.github.io/styleguide/jsguide.html

**Comment by rgraue** [comment]
We already have linters that do this. just run `npm run lint` and `npm runt format`

**Comment by rgraue** [comment]
#40 covers the unit test conventions of the standard
